{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Отлов ошибок"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Для вышеописанного случая как раз и нужна конструкция **try catch** для отлова ошибок в момент их создания. \n",
    "\n",
    "\n",
    "\n",
    "При помощи данной конструкции вы можете отслеживать ошибки различных форматов и событий. Можно отследить неверное открытие файла, можно отследить неверное подключение класса, можно отследить неверное написание переменной или функции, да чего уж там, можно отследить даже деление чисел на ноль."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Реализация конструкций try catch**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "vscode": {
     "languageId": "cpp"
    }
   },
   "outputs": [],
   "source": [
    "try { // В блоке try мы пытаемся выполнить какой-либо код\n",
    "\tif (variable == 0) // Проверяем делитель на ноль\n",
    "\t\tthrow 277; // Запускаем исключение и передаем в него параметр\n",
    "\t\n",
    "\tcout << something / variable << endl; \n",
    "} catch(std::exception& i) { // Здесь отлавливаем переданную ошибку\n",
    "\tcout << \"Нам очень повезло!\" << endl;\n",
    "\tcout << \"Удалось избежать ошибки: \" << i.what() << \" - на 0 делить нельзя!\";\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "В коде выше представлен очень простой пример использования исключений. Не обращайте внимание на его простоту, так как главное это рассмотреть общую конструкцию блока **try catch**.\n",
    "\n",
    "\n",
    "\n",
    "При использовании такой конструкции, какая бы ошибка не получилась в ходе программы сама программа работать не перестанет и пользователь не получить плохой опыт в её использовании.\n",
    "\n",
    "\n",
    "\n",
    "Если необходимо отследить несколько классов с ошибками, то можно добавить несколько блоков **catch**. Все они добавляются друг под другом точно также как в условных операторах.\n",
    "\n",
    "**std::exception** - тип данных, который выводит всю инфу об ошибке. Если хряпнуть **i.what()** - то получим результат."
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
